files: ["test.txt"]
detect: [["err"]]
excerpt_size: 100
mail:
    name: "Cyclops by Faruq Rasid"
    email: "me@gmail.com"
    password: ""
    to: "hello@gmail.com"
    address: "smtp.gmail.com"
    port: 587